# Generated by Django 4.2.4 on 2023-08-13 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0005_alter_booking_date_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': 'Встреча', 'verbose_name_plural': 'Встречи'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Место для встреч', 'verbose_name_plural': 'Места для встреч'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Билет на встречу', 'verbose_name_plural': 'Билеты на встречи'},
        ),
    ]
