# Generated by Django 4.2.4 on 2023-08-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0006_alter_booking_options_alter_meeting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(default='', help_text='Описание места', max_length=500, verbose_name='Описание'),
        ),
    ]
