# Generated by Django 4.2.4 on 2023-08-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0008_alter_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default=None, help_text='Имя участника в Telegram', max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='member',
            name='surname',
            field=models.CharField(default=None, help_text='Фамилия участник в Telegram', max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(default='', help_text='Описание мест', max_length=500, verbose_name='Описание'),
        ),
    ]
