# Generated by Django 4.2.4 on 2023-08-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0010_alter_member_surname_alter_place_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default=None, help_text='Имя участника в Telegra', max_length=200, verbose_name='Имя'),
        ),
    ]
