# Generated by Django 4.2.4 on 2023-08-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0012_alter_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default=None, help_text='Имя участника в Telegram', max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='member',
            name='surname',
            field=models.CharField(default=None, help_text='Фамилия участника в Telegram', max_length=200, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(default='', help_text='Описание места', max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
