# Generated by Django 4.2.4 on 2023-08-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0013_alter_member_name_alter_member_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='Имя участника в Telegram', max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='member',
            name='surname',
            field=models.CharField(blank=True, default=None, help_text='Фамилия участника в Telegram', max_length=200, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Описание места', max_length=500, null=True, verbose_name='Описание'),
        ),
    ]
