# Generated by Django 4.2.4 on 2023-08-15 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0016_alter_booking_member_id_alter_booking_ticket_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='member_id',
            field=models.ForeignKey(help_text="Участник встречи из таблицы 'Участники'", on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='architecture.member', verbose_name='Участник'),
        ),
    ]
