# Generated by Django 4.2.4 on 2023-08-26 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0017_alter_booking_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='member_id',
            field=models.ForeignKey(help_text="Участник встречи из таблицы 'Участники'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='architecture.member', verbose_name='Участник'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ticket_id',
            field=models.ForeignKey(help_text="Билет на встречу из таблицы 'Билеты на встречи'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='architecture.ticket', verbose_name='Билет на встречу'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='place_id',
            field=models.ForeignKey(help_text="Место встречи из таблицы 'Места для встреч'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='architecture.place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='meeting_id',
            field=models.ForeignKey(help_text="Встреча из таблицы 'Встречи'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='architecture.meeting', verbose_name='Встреча'),
        ),
    ]
