# Generated by Django 4.2.4 on 2023-09-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0019_alter_member_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_confirm_paid',
            field=models.BooleanField(default=False, help_text='Участник подтвердил оплату билета на встречу или нет', verbose_name='Участник подтвердил оплату'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Мы подтвердили оплату билета на встречу или нет', verbose_name='Статус оплаты'),
        ),
    ]
